# -*- coding: utf-8 -*-
"""Python_fundamentals1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTjdXG-vQBUIjSK-ub_lqP-GuK6r4xpG

# Welcome to the Fundamentals of Python!

## Today's lessons: Variables, Loops and Functions
First, as per tradition: We print "Hello World"
"""

print("Hello World!")

"""###Variables

Strings --> Text, such as "Hello World". Mark strings with two quotes, like this: "Example"

Integers --> Numbers, such as 1, 3, or 7. These are _full numbers_. For partial numbers, we use **floats**. 

Lists --> A collection of elements. We save them in square brackets, and seperate every element by commas, like so: [1, 2, 3, 4, 5]

#### Strings
"""

a = "Hello World!"

print(a)

"""####Integers"""

b = 15

print(b + 3)

"""####Lists"""

friends_list = ["Tom", "Susan", "Mary", "Elisabeth", "Dirk"]

print(friends_list)

"""###Loops

What if I want to print out all of these people's names seperately? Easy: Use a loop! 


"""

for friend in friends_list:
  print("My friends name is:")
  print(friend)
  print("And they are awesome!")
  print("")

"""We can also use loops to do something "X" amount of times: Like adding 1 to a number"""

base_number = 0

for number in range(0,10):
  base_number = base_number + 1

print(base_number)

"""### Functions

Functions are a basic template of general instructions that can be used for different things. Think of it as a tax calculator for example: Different people's incomes (inputs) are taxed differently (output). 

So, first you need to define the **template** itself:
"""

def my_function(list): 
  length = len(list)
  print("This list has {} elements in it!".format(length))

"""Next, you use your template with an input to get the output:"""

my_function(friends_list)

"""Below are a few challenges you can solve while we help everyone prepare for the second part of this Workshop. And remember: Google is your best friend! 

1. Create a list containing all numbers from 0 to 10'000 using a for-loop

2. Write a function that adds all the elements in a list together

3. Write a function that takes in the yearly salary of a person, and gives back how much they need to pay in income taxes with a tax-rate fo 20%.

4. Research if-else statements on Google. Then re-write the function in 3 with the swiss income taxes: 
https://www.fedlex.admin.ch/eli/cc/1991/1184_1184_1184/de#part_2/tit_2/chap_5/sec_1

5. Write a different function that takes in two lists of people, and match them up randomly - that way, everyone gets to hang out with someone they don't know yet! 
"""